??build????

diff --git a/build b/build
--- a/build
+++ b/build
@@ -9,23 +9,19 @@ do
 	case "$optname" in
 		"n") NO_COMPRESS=1;;
 		"o") OUTFILE=$OPTARG;;
-		"?") echo "Unknown option $OPTARG"; exit 1;;
-		":") echo "Missing argument value for option $OPTARG"; exit 1;;
+		"?") echo "Unknown option -$OPTARG"; exit 1;;
+		":") echo "Missing argument value for option -$OPTARG"; exit 1;;
 	esac
 done
-if [ $NO_COMPRESS ]
-then
-	sed 's/#settings.css#/'"${CSS}"'/;s/#settings.html#/'"${HTML}"'/' weiboFilter.user.js > $OUTFILE
-	exit 1
-fi
+sed 's/#settings.css#/'"${CSS}"'/;s/#settings.html#/'"${HTML}"'/' weiboFilter.user.js > $OUTFILE
+[ $NO_COMPRESS ] && exit 0
 head -n 14 weiboFilter.user.js > weiboFilter.user.head.js
-sed 's/#settings.css#/'"${CSS}"'/;s/#settings.html#/'"${HTML}"'/' weiboFilter.user.js > weiboFilter.user.body.js
 if [ ! -f compiler.jar ]
 then
 	wget -q http://closure-compiler.googlecode.com/files/compiler-latest.tar.gz
 	tar -xzf compiler-latest.tar.gz compiler.jar
 	rm compiler-latest.tar.gz
 fi
-java -jar compiler.jar --charset=UTF-8 --compilation_level SIMPLE_OPTIMIZATIONS --js=weiboFilter.user.body.js --js_output_file=weiboFilter.user.body.compiled.js
-cat weiboFilter.user.head.js weiboFilter.user.body.compiled.js > $OUTFILE
-rm weiboFilter.user.head.js weiboFilter.user.body.js weiboFilter.user.body.compiled.js
+java -jar compiler.jar --charset=UTF-8 --compilation_level SIMPLE_OPTIMIZATIONS --js=$OUTFILE --js_output_file=weiboFilter.user.body.js
+cat weiboFilter.user.head.js weiboFilter.user.body.js > $OUTFILE
+rm weiboFilter.user.head.js weiboFilter.user.body.js
